version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: shareit-db
    environment:
      POSTGRES_USER: katya
      POSTGRES_PASSWORD: 1223
      POSTGRES_DB: shareit_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
